### ISSUE TITLE
PTP Daemon usage

### ISSUE THREAD

**Issue by batanena** [markotikvic/QNX-BBB#1]
Hi, 

Can you please let me know which PTP Daemon did you use to verify this driver functionality? I am in the process of developing an Ethernet driver for HW that supports PTP time stamping. But not able to figure out which PTP Daemon to use to verify the functionality. Please let me know the usage of that daemon as well. 

Thanks.

**Comment by markotikvic** [comment]
Hi,

This repo is just a backup version after I managed to install the image on Beaglebone with USART interfaces configured in the build script. I have not used PTP deamon with QNX so I can't really help you with that. Sorry. I would recommend using their man pages (I think they host them on the website).  

Good luck.
